/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 4.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * LivenessApi - axios parameter creator
 * @export
 */
export const LivenessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Liveness 2.0 metadata
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livenessMetadata: async (eRRORUNKNOWN: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eRRORUNKNOWN' is not null or undefined
            assertParamExists('livenessMetadata', 'eRRORUNKNOWN', eRRORUNKNOWN)
            const localVarPath = `/api/v2/liveness/metadata`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (eRRORUNKNOWN !== undefined) {
                localVarQueryParameter[''] = eRRORUNKNOWN;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Liveness 2.0 portrait
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livenessPortrait: async (eRRORUNKNOWN: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eRRORUNKNOWN' is not null or undefined
            assertParamExists('livenessPortrait', 'eRRORUNKNOWN', eRRORUNKNOWN)
            const localVarPath = `/api/v2/liveness/portrait`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (eRRORUNKNOWN !== undefined) {
                localVarQueryParameter[''] = eRRORUNKNOWN;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Liveness 2.0 video
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livenessVideo: async (eRRORUNKNOWN: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eRRORUNKNOWN' is not null or undefined
            assertParamExists('livenessVideo', 'eRRORUNKNOWN', eRRORUNKNOWN)
            const localVarPath = `/api/v2/liveness/video`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (eRRORUNKNOWN !== undefined) {
                localVarQueryParameter[''] = eRRORUNKNOWN;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LivenessApi - functional programming interface
 * @export
 */
export const LivenessApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LivenessApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Liveness 2.0 metadata
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async livenessMetadata(eRRORUNKNOWN: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.livenessMetadata(eRRORUNKNOWN, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Liveness 2.0 portrait
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async livenessPortrait(eRRORUNKNOWN: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.livenessPortrait(eRRORUNKNOWN, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Liveness 2.0 video
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async livenessVideo(eRRORUNKNOWN: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.livenessVideo(eRRORUNKNOWN, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LivenessApi - factory interface
 * @export
 */
export const LivenessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LivenessApiFp(configuration)
    return {
        /**
         * 
         * @summary Liveness 2.0 metadata
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livenessMetadata(eRRORUNKNOWN: number, options?: any): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.livenessMetadata(eRRORUNKNOWN, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Liveness 2.0 portrait
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livenessPortrait(eRRORUNKNOWN: number, options?: any): AxiosPromise<any> {
            return localVarFp.livenessPortrait(eRRORUNKNOWN, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Liveness 2.0 video
         * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livenessVideo(eRRORUNKNOWN: number, options?: any): AxiosPromise<any> {
            return localVarFp.livenessVideo(eRRORUNKNOWN, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LivenessApi - object-oriented interface
 * @export
 * @class LivenessApi
 * @extends {BaseAPI}
 */
export class LivenessApi extends BaseAPI {
    /**
     * 
     * @summary Liveness 2.0 metadata
     * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LivenessApi
     */
    public livenessMetadata(eRRORUNKNOWN: number, options?: AxiosRequestConfig) {
        return LivenessApiFp(this.configuration).livenessMetadata(eRRORUNKNOWN, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Liveness 2.0 portrait
     * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LivenessApi
     */
    public livenessPortrait(eRRORUNKNOWN: number, options?: AxiosRequestConfig) {
        return LivenessApiFp(this.configuration).livenessPortrait(eRRORUNKNOWN, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Liveness 2.0 video
     * @param {number} eRRORUNKNOWN ID of the current liveness transaction.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LivenessApi
     */
    public livenessVideo(eRRORUNKNOWN: number, options?: AxiosRequestConfig) {
        return LivenessApiFp(this.configuration).livenessVideo(eRRORUNKNOWN, options).then((request) => request(this.axios, this.basePath));
    }
}
