/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddImageToPersonRequest } from '../models';
// @ts-ignore
import type { AddImageToPersonResponse } from '../models';
// @ts-ignore
import type { GroupPage } from '../models';
// @ts-ignore
import type { ImagePage } from '../models';
// @ts-ignore
import type { OperationLog } from '../models';
// @ts-ignore
import type { Person } from '../models';
// @ts-ignore
import type { PersonFields } from '../models';
// @ts-ignore
import type { PersonToUpdateFields } from '../models';
/**
 * PersonApi - axios parameter creator
 */
export const PersonApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add person image
         * @param {string} personId Person ID.
         * @param {AddImageToPersonRequest} addImageToPersonRequest Image to add.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addImageToPerson: async (personId: string, addImageToPersonRequest: AddImageToPersonRequest, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('addImageToPerson', 'personId', personId)
            // verify required parameter 'addImageToPersonRequest' is not null or undefined
            assertParamExists('addImageToPerson', 'addImageToPersonRequest', addImageToPersonRequest)
            const localVarPath = `/api/persons/{personId}/images`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addImageToPersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create person
         * @param {PersonFields} personFields 
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPerson: async (personFields: PersonFields, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personFields' is not null or undefined
            assertParamExists('createPerson', 'personFields', personFields)
            const localVarPath = `/api/persons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personFields, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete image of person
         * @param {string} personId Person ID.
         * @param {string} imageId Image ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteImageOfPerson: async (personId: string, imageId: string, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('deleteImageOfPerson', 'personId', personId)
            // verify required parameter 'imageId' is not null or undefined
            assertParamExists('deleteImageOfPerson', 'imageId', imageId)
            const localVarPath = `/api/persons/{personId}/images/{imageId}`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)))
                .replace(`{${"imageId"}}`, encodeURIComponent(String(imageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete person
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePerson: async (personId: string, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('deletePerson', 'personId', personId)
            const localVarPath = `/api/persons/{personId}`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get person groups
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {number} [page] The page number to get a list of persons or groups.
         * @param {number} [size] The page size with a list of persons or groups, items.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllGroupsByPersonId: async (personId: string, xRequestID?: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('getAllGroupsByPersonId', 'personId', personId)
            const localVarPath = `/api/persons/{personId}/groups`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get person images
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {number} [page] The page number to get a list of persons or groups.
         * @param {number} [size] The page size with a list of persons or groups, items.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllImagesByPersonId: async (personId: string, xRequestID?: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('getAllImagesByPersonId', 'personId', personId)
            const localVarPath = `/api/persons/{personId}/images`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get person image by id
         * @param {string} personId Person ID.
         * @param {string} imageId Image ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImageOfPerson: async (personId: string, imageId: string, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('getImageOfPerson', 'personId', personId)
            // verify required parameter 'imageId' is not null or undefined
            assertParamExists('getImageOfPerson', 'imageId', imageId)
            const localVarPath = `/api/persons/{personId}/images/{imageId}`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)))
                .replace(`{${"imageId"}}`, encodeURIComponent(String(imageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get person
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerson: async (personId: string, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('getPerson', 'personId', personId)
            const localVarPath = `/api/persons/{personId}`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update person
         * @param {string} personId Person ID.
         * @param {PersonToUpdateFields} personToUpdateFields Request body for the Person to update.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson: async (personId: string, personToUpdateFields: PersonToUpdateFields, xRequestID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('updatePerson', 'personId', personId)
            // verify required parameter 'personToUpdateFields' is not null or undefined
            assertParamExists('updatePerson', 'personToUpdateFields', personToUpdateFields)
            const localVarPath = `/api/persons/{personId}`
                .replace(`{${"personId"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personToUpdateFields, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonApi - functional programming interface
 */
export const PersonApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PersonApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add person image
         * @param {string} personId Person ID.
         * @param {AddImageToPersonRequest} addImageToPersonRequest Image to add.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addImageToPerson(personId: string, addImageToPersonRequest: AddImageToPersonRequest, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddImageToPersonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addImageToPerson(personId, addImageToPersonRequest, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.addImageToPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create person
         * @param {PersonFields} personFields 
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPerson(personFields: PersonFields, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Person>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPerson(personFields, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.createPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete image of person
         * @param {string} personId Person ID.
         * @param {string} imageId Image ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteImageOfPerson(personId: string, imageId: string, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteImageOfPerson(personId, imageId, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.deleteImageOfPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete person
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePerson(personId: string, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePerson(personId, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.deletePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get person groups
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {number} [page] The page number to get a list of persons or groups.
         * @param {number} [size] The page size with a list of persons or groups, items.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllGroupsByPersonId(personId: string, xRequestID?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllGroupsByPersonId(personId, xRequestID, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.getAllGroupsByPersonId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get person images
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {number} [page] The page number to get a list of persons or groups.
         * @param {number} [size] The page size with a list of persons or groups, items.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllImagesByPersonId(personId: string, xRequestID?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImagePage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllImagesByPersonId(personId, xRequestID, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.getAllImagesByPersonId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get person image by id
         * @param {string} personId Person ID.
         * @param {string} imageId Image ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getImageOfPerson(personId: string, imageId: string, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getImageOfPerson(personId, imageId, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.getImageOfPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get person
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerson(personId: string, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Person>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPerson(personId, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.getPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update person
         * @param {string} personId Person ID.
         * @param {PersonToUpdateFields} personToUpdateFields Request body for the Person to update.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePerson(personId: string, personToUpdateFields: PersonToUpdateFields, xRequestID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePerson(personId, personToUpdateFields, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonApi.updatePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PersonApi - factory interface
 */
export const PersonApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PersonApiFp(configuration)
    return {
        /**
         * 
         * @summary Add person image
         * @param {string} personId Person ID.
         * @param {AddImageToPersonRequest} addImageToPersonRequest Image to add.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addImageToPerson(personId: string, addImageToPersonRequest: AddImageToPersonRequest, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<AddImageToPersonResponse> {
            return localVarFp.addImageToPerson(personId, addImageToPersonRequest, xRequestID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create person
         * @param {PersonFields} personFields 
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPerson(personFields: PersonFields, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Person> {
            return localVarFp.createPerson(personFields, xRequestID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete image of person
         * @param {string} personId Person ID.
         * @param {string} imageId Image ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteImageOfPerson(personId: string, imageId: string, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteImageOfPerson(personId, imageId, xRequestID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete person
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePerson(personId: string, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePerson(personId, xRequestID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get person groups
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {number} [page] The page number to get a list of persons or groups.
         * @param {number} [size] The page size with a list of persons or groups, items.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllGroupsByPersonId(personId: string, xRequestID?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<GroupPage> {
            return localVarFp.getAllGroupsByPersonId(personId, xRequestID, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get person images
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {number} [page] The page number to get a list of persons or groups.
         * @param {number} [size] The page size with a list of persons or groups, items.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllImagesByPersonId(personId: string, xRequestID?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ImagePage> {
            return localVarFp.getAllImagesByPersonId(personId, xRequestID, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get person image by id
         * @param {string} personId Person ID.
         * @param {string} imageId Image ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImageOfPerson(personId: string, imageId: string, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getImageOfPerson(personId, imageId, xRequestID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get person
         * @param {string} personId Person ID.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerson(personId: string, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Person> {
            return localVarFp.getPerson(personId, xRequestID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update person
         * @param {string} personId Person ID.
         * @param {PersonToUpdateFields} personToUpdateFields Request body for the Person to update.
         * @param {string} [xRequestID] Request header label.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson(personId: string, personToUpdateFields: PersonToUpdateFields, xRequestID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updatePerson(personId, personToUpdateFields, xRequestID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonApi - object-oriented interface
 */
export class PersonApi extends BaseAPI {
    /**
     * 
     * @summary Add person image
     * @param {string} personId Person ID.
     * @param {AddImageToPersonRequest} addImageToPersonRequest Image to add.
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addImageToPerson(personId: string, addImageToPersonRequest: AddImageToPersonRequest, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).addImageToPerson(personId, addImageToPersonRequest, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create person
     * @param {PersonFields} personFields 
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPerson(personFields: PersonFields, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).createPerson(personFields, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete image of person
     * @param {string} personId Person ID.
     * @param {string} imageId Image ID.
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteImageOfPerson(personId: string, imageId: string, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).deleteImageOfPerson(personId, imageId, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete person
     * @param {string} personId Person ID.
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePerson(personId: string, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).deletePerson(personId, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get person groups
     * @param {string} personId Person ID.
     * @param {string} [xRequestID] Request header label.
     * @param {number} [page] The page number to get a list of persons or groups.
     * @param {number} [size] The page size with a list of persons or groups, items.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllGroupsByPersonId(personId: string, xRequestID?: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).getAllGroupsByPersonId(personId, xRequestID, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get person images
     * @param {string} personId Person ID.
     * @param {string} [xRequestID] Request header label.
     * @param {number} [page] The page number to get a list of persons or groups.
     * @param {number} [size] The page size with a list of persons or groups, items.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllImagesByPersonId(personId: string, xRequestID?: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).getAllImagesByPersonId(personId, xRequestID, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get person image by id
     * @param {string} personId Person ID.
     * @param {string} imageId Image ID.
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getImageOfPerson(personId: string, imageId: string, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).getImageOfPerson(personId, imageId, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get person
     * @param {string} personId Person ID.
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPerson(personId: string, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).getPerson(personId, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update person
     * @param {string} personId Person ID.
     * @param {PersonToUpdateFields} personToUpdateFields Request body for the Person to update.
     * @param {string} [xRequestID] Request header label.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePerson(personId: string, personToUpdateFields: PersonToUpdateFields, xRequestID?: string, options?: RawAxiosRequestConfig) {
        return PersonApiFp(this.configuration).updatePerson(personId, personToUpdateFields, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }
}

