/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SearchBadParams } from '../models';
// @ts-ignore
import type { SearchPerson } from '../models';
// @ts-ignore
import type { SearchRequest } from '../models';
// @ts-ignore
import type { SearchResult } from '../models';
/**
 * SearchApi - axios parameter creator
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Find person by image in groups
         * @param {SearchRequest} searchRequest 
         * @param {string} [xRequestID] Request header label.
         * @param {boolean} [withImages] When enabled, the response includes Base64-encoded images of matched persons. Each entry in the &#x60;persons&#x60; array contains an &#x60;images&#x60; field with image IDs and content. If omitted or set to false, images are excluded.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (searchRequest: SearchRequest, xRequestID?: string, withImages?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchRequest' is not null or undefined
            assertParamExists('search', 'searchRequest', searchRequest)
            const localVarPath = `/api/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (withImages !== undefined) {
                localVarQueryParameter['withImages'] = withImages;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xRequestID != null) {
                localVarHeaderParameter['X-RequestID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Find person by image in groups
         * @param {SearchRequest} searchRequest 
         * @param {string} [xRequestID] Request header label.
         * @param {boolean} [withImages] When enabled, the response includes Base64-encoded images of matched persons. Each entry in the &#x60;persons&#x60; array contains an &#x60;images&#x60; field with image IDs and content. If omitted or set to false, images are excluded.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(searchRequest: SearchRequest, xRequestID?: string, withImages?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(searchRequest, xRequestID, withImages, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SearchApi - factory interface
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * 
         * @summary Find person by image in groups
         * @param {SearchRequest} searchRequest 
         * @param {string} [xRequestID] Request header label.
         * @param {boolean} [withImages] When enabled, the response includes Base64-encoded images of matched persons. Each entry in the &#x60;persons&#x60; array contains an &#x60;images&#x60; field with image IDs and content. If omitted or set to false, images are excluded.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(searchRequest: SearchRequest, xRequestID?: string, withImages?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<SearchResult> {
            return localVarFp.search(searchRequest, xRequestID, withImages, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchApi - object-oriented interface
 */
export class SearchApi extends BaseAPI {
    /**
     * 
     * @summary Find person by image in groups
     * @param {SearchRequest} searchRequest 
     * @param {string} [xRequestID] Request header label.
     * @param {boolean} [withImages] When enabled, the response includes Base64-encoded images of matched persons. Each entry in the &#x60;persons&#x60; array contains an &#x60;images&#x60; field with image IDs and content. If omitted or set to false, images are excluded.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(searchRequest: SearchRequest, xRequestID?: string, withImages?: boolean, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).search(searchRequest, xRequestID, withImages, options).then((request) => request(this.axios, this.basePath));
    }
}

