/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddImageToPersonRequestData } from './add-image-to-person-request-data';
// May contain unused imports in some cases
// @ts-ignore
import type { AddImageToPersonRequestImage } from './add-image-to-person-request-image';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionLabels } from './transaction-labels';

/**
 * @type AddImageToPersonRequest
 * Image in the request data, includes image and contentType.
 */
export type AddImageToPersonRequest = AddImageToPersonRequestData & TransactionLabels;


