/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceAlignTypeQuality } from './face-align-type-quality';

/**
 * Face image alignment and cutting, includes type, pad, cropSize.
 * @export
 * @interface Align
 */
export interface Align {
    /**
     * 
     * @type {FaceAlignTypeQuality}
     * @memberof Align
     */
    type?: FaceAlignTypeQuality;
    /**
     * 
     * @type {Array<number>}
     * @memberof Align
     */
    pad?: Array<number>;
    /**
     * The resize value in case type matches this value. It it doesn\'t match, no resize is done.
     * @type {Array<number>}
     * @memberof Align
     */
    cropSize?: Array<number>;
}


