/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceAttribute } from './face-attribute';

/**
 * The configuration that defines the list of returned attribute check characteristics.
 */
export interface AttributeConfig {
    'name'?: FaceAttribute;
}



