/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DetectionFace } from './detection-face';

/**
 * 
 * @export
 * @interface CompareImageDetection
 */
export interface CompareImageDetection {
    /**
     * 
     * @type {Array<DetectionFace>}
     * @memberof CompareImageDetection
     */
    faces?: Array<DetectionFace>;
    /**
     * 
     * @type {number}
     * @memberof CompareImageDetection
     */
    imageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof CompareImageDetection
     */
    status?: number;
}


