/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CompareImageDetection } from './compare-image-detection';
import { CompareImageResult } from './compare-image-result';

/**
 * 
 * @export
 * @interface CompareResponseAllOf
 */
export interface CompareResponseAllOf {
    /**
     * 
     * @type {Array<CompareImageResult>}
     * @memberof CompareResponseAllOf
     */
    results: Array<CompareImageResult>;
    /**
     * 
     * @type {Array<CompareImageDetection>}
     * @memberof CompareResponseAllOf
     */
    detections: Array<CompareImageDetection>;
}


