/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CompareResponseFields } from './compare-response-fields';

/**
 * 
 * @export
 * @interface CompareResponse
 */
export interface CompareResponse {
    /**
     * 
     * @type {Array<CompareResponseFields>}
     * @memberof CompareResponse
     */
    results?: Array<CompareResponseFields>;
}


