/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CompareImage } from './compare-image';

/**
 * 
 * @export
 * @interface CompareRequest
 */
export interface CompareRequest {
    /**
     * 
     * @type {boolean}
     * @memberof CompareRequest
     */
    thumbnails?: boolean;
    /**
     * 
     * @type {Array<CompareImage>}
     * @memberof CompareRequest
     */
    images: Array<CompareImage>;
}


