/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceAlignTypeQuality } from './face-align-type-quality';

/**
 * 
 * @export
 * @interface Crop
 */
export interface Crop {
    /**
     * 
     * @type {FaceAlignTypeQuality}
     * @memberof Crop
     */
    'type'?: FaceAlignTypeQuality;
    /**
     * 
     * @type {Array<number>}
     * @memberof Crop
     */
    'padColor'?: Array<number>;
    /**
     * The resize value in case type matches this value. It it doesn\'t, no resize is done.
     * @type {Array<number>}
     * @memberof Crop
     */
    'size'?: Array<number>;
    /**
     * Whether to return the coordinates of the rectangle with the face in the original image prepared for the face crop.
     * @type {boolean}
     * @memberof Crop
     */
    'returnOriginalRect'?: boolean;
}

