/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DepthLivenessItem } from './depth-liveness-item';

/**
 * 
 * @export
 * @interface DepthLiveness
 */
export interface DepthLiveness {
    /**
     * 
     * @type {Array<DepthLivenessItem>}
     * @memberof DepthLiveness
     */
    images?: Array<DepthLivenessItem>;
}


