/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageData } from './image-data';

/**
 * 
 * @export
 * @interface DepthLivenessItem
 */
export interface DepthLivenessItem {
    /**
     * 
     * @type {ImageData}
     * @memberof DepthLivenessItem
     */
    dataScene: ImageData;
    /**
     * 
     * @type {ImageData}
     * @memberof DepthLivenessItem
     */
    dataDepth: ImageData;
    /**
     * Normalized factor for color depth.
     * @type {number}
     * @memberof DepthLivenessItem
     */
    depthScale: number;
}


