/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



export interface DetailItem {
    /**
     * The name of the attribute.
     */
    'name'?: string;
}

