/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AttributesData } from './attributes-data';
// May contain unused imports in some cases
// @ts-ignore
import type { DetailItem } from './detail-item';

/**
 * @type DetectAttributesDetails
 */
export type DetectAttributesDetails = AttributesData & DetailItem;


