/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageData } from './image-data';

/**
 * 
 * @export
 * @interface DetectRequest
 */
export interface DetectRequest {
    /**
     * 
     * @type {ImageData}
     * @memberof DetectRequest
     */
    image?: ImageData;
    /**
     * True - main face; false - all faces.
     * @type {boolean}
     * @memberof DetectRequest
     */
    only_central_face?: boolean;
}


