/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageData } from './image-data';

/**
 * 
 * @export
 * @interface DetectRequest
 */
export interface DetectRequest {
    /**
     * 
     * @type {string}
     * @memberof DetectRequest
     */
    tag?: string;
    /**
     * 
     * @type {ImageData}
     * @memberof DetectRequest
     */
    image?: ImageData;
    /**
     * Enable formatted detections\' thumbnails in the response
     * @type {boolean}
     * @memberof DetectRequest
     */
    thumbnails?: boolean;
    /**
     * Enable face attributions detection, such as age or emotion and etc.
     * @type {boolean}
     * @memberof DetectRequest
     */
    attributes?: boolean;
    /**
     * True - main face; false - all faces.
     * @type {boolean}
     * @memberof DetectRequest
     */
    onlyCentralFace?: boolean;
}


