/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DetectAttributesDetails } from './detect-attributes-details';
// May contain unused imports in some cases
// @ts-ignore
import type { DetectDetailsMeta } from './detect-details-meta';

/**
 * @type DetectionAttributesDetailsInner
 */
export type DetectionAttributesDetailsInner = DetectAttributesDetails | DetectDetailsMeta;


