/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DetectionAttributes } from './detection-attributes';
// May contain unused imports in some cases
// @ts-ignore
import type { DetectionQuality } from './detection-quality';

export interface Detection {
    /**
     * Base64-encoded image.
     */
    'crop'?: string;
    'attributes'?: DetectionAttributes;
    /**
     * Absolute coordinates (X,Y) of five points of each detected face: left eye, right eye, nose, left point of lips, right point of lips.
     */
    'landmarks': Array<Array<number>>;
    'quality'?: DetectionQuality;
    /**
     * The rectangular area of a detected face that is represented by a set of four elements: the X and Y coordinates of the top-left point, and the width and height dimensions of the rectangle.
     */
    'roi': Array<number>;
}

