/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceQualityConfigName } from './face-quality-config-name';
// May contain unused imports in some cases
// @ts-ignore
import type { QualityDetail } from './quality-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { QualityDetailsGroups } from './quality-details-groups';

/**
 * The portrait quality assessment results, see [Face Image Quality Characteristics](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/usage/face-detection/face-image-quality-check/). If not set in request, no quality check is performed.
 */
export interface DetectionQuality {
    /**
     * Non-compliant assessment characteristics.
     */
    'nonCompliant'?: Array<FaceQualityConfigName>;
    /**
     * Assessment results for each [group of characteristics](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/face-image-quality-groups/).
     */
    'detailsGroups'?: Array<QualityDetailsGroups>;
    /**
     * Assessment characteristics that were set in the request.
     */
    'details'?: Array<QualityDetail>;
    /**
     * Returns the estimated portrait quality assessment result, a number from `0` to `1`, where `1` is for absolute compliance.
     */
    'score'?: number;
    /**
     * Server processing time for quality assessment, ms.
     */
    'elapsedTime'?: number;
}

