/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum FaceQualityUnit {
    QUALITY_UNIT_PIXELS = 'pixels',
    QUALITY_UNIT_RELATIVE = 'relative',
    QUALITY_UNIT_PSC = 'pcs',
    QUALITY_UNIT_DEGREES = 'degrees',
    QUALITY_UNIT_PERCENT = 'percent',
    QUALITY_UNIT_BITS = 'bits',
    QUALITY_UNIT_QUANTITY = 'quantity'
}



