/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The aspect ratio according to which alignment is performed.
 * @export
 * @enum {string}
 */

export const FaceAlignTypeQuality = {
    ALIGN_3x4: 0,
    ALIGN_4x5: 1,
    ALIGN_2x3: 2,
    ALIGN_1x1: 3,
    ALIGN_7x9: 4
} as const;

export type FaceAlignTypeQuality = typeof FaceAlignTypeQuality[keyof typeof FaceAlignTypeQuality];



