/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum FaceQualityConfigName {
    BACKGROUND_UNIFORMITY = 'BackgroundUniformity',
    BLUR_LEVEL = 'BlurLevel',
    CONTACT_LENSES = 'ContactLenses',
    DARK_GLASSES = 'DarkGlasses',
    EXPRESSION_LEVEL = 'ExpressionLevel',
    EYES_DISTANCE = 'EyeLeftClosed',
    EYES_RED = 'EyeLeftCoveredWithHair',
    EYE_LEFT_CLOSED = 'EyeLeftOccluded',
    EYE_LEFT_COVERED_WITH_HAIR = 'EyeRightClosed',
    EYE_LEFT_OCCLUDED = 'EyeRightCoveredWithHair',
    EYE_RIGHT_CLOSED = 'EyeRightOccluded',
    EYE_RIGHT_COVERED_WITH_HAIR = 'EyesDistance',
    EYE_RIGHT_OCCLUDED = 'EyesRed',
    FACE_DYNAMIC_RANGE = 'FaceDynamicRange',
    FACE_GLARE = 'FaceGlare',
    FACE_MID_POINT_HORIZONTAL_POSITION = 'FaceMidPointHorizontalPosition',
    FACE_MID_POINT_VERTICAL_POSITION = 'FaceMidPointVerticalPosition',
    FACE_OCCLUDED = 'FaceOccluded',
    FOREHEAD_COVERING = 'ForeheadCovering',
    FRAMES_TOO_HEAVY = 'FramesTooHeavy',
    HEAD_COVERING = 'HeadCovering',
    HEAD_HEIGHT_RATIO = 'HeadHeightRatio',
    HEAD_WIDTH_RATIO = 'HeadWidthRatio',
    IMAGE_CHANNELS_NUMBER = 'ImageChannelsNumber',
    IMAGE_HEIGHT = 'ImageHeight',
    IMAGE_WIDTH = 'ImageWidth',
    IMAGE_WIDTH_TO_HEIGHT = 'ImageWidthToHeight',
    MOUTH_OPEN = 'MouthOpen',
    NOISE_LEVEL = 'NoiseLevel',
    OFF_GAZE = 'OffGaze',
    OTHER_FACES = 'OtherFaces',
    PADDING_RATIO = 'PaddingRatio',
    PITCH = 'Pitch',
    REFLECTION_ON_GLASSES = 'ReflectionOnGlasses',
    ROLL = 'Roll',
    SHADOWS_ON_BACKGROUND = 'ShadowsOnBackground',
    SHADOWS_ON_FACE = 'ShadowsOnFace',
    SHOULDERS_POSE = 'ShouldersPose',
    SMILE = 'Smile',
    STRONG_MAKEUP = 'StrongMakeup',
    TOO_DARK = 'TooDark',
    TOO_LIGHT = 'TooLight',
    UNNATURAL_SKIN_TONE = 'UnnaturalSkinTone',
    YAW = 'Yaw'
}



