/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * The processing status returned for each quality characteristic, see the [FaceImageQualityStatus enum](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/face-image-quality-status/).
 */

export enum FaceImageQualityStatus {
    QUALITY_STATUS_FALSE = 0,
    QUALITY_STATUS_TRUE = 1,
    QUALITY_STATUS_UNDETERMINED = 2
}



