/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DetectionFace } from './detection-face';
// May contain unused imports in some cases
// @ts-ignore
import type { FacesResponseData } from './faces-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonWithImages } from './person-with-images';

/**
 * @type FacesResponse
 */
export type FacesResponse = DetectionFace & FacesResponseData;


