/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * The aspect ratio according to which face alignment is performed. See the [FaceImageQualityAlignType enum](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/face-image-quality-align-type/). To get a thumbnail with aspect ratio 3:4, set `0`.
 */

export enum FaceImageQualityAlignType {
    ALIGN_3x4 = 0,
    ALIGN_4x5 = 1,
    ALIGN_2x3 = 2,
    ALIGN_1x1 = 3,
    ALIGN_7x9 = 4
}



