/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Face image quality group types for face image quality assessment.
 * @export
 * @enum {string}
 */

export const FaceImageQualityGroupsStrings = {
    IMAGE_CHARACTERISTICS: 'ImageCharacteristics',
    HEAD_SIZE_AND_POSITIONS: 'HeadSizeAndPosition',
    FACE_QUALITY: 'FaceQuality',
    EYES_CHARACTERISTICS: 'EyesCharacteristics',
    SHADOWS_AND_LIGHTNING: 'ShadowsAndLightning',
    POSE_AND_EXPRESSION: 'PoseAndExpression',
    HEAD_OCCLUSION: 'HeadOcclusion',
    BACKGROUND: 'Background'
} as const;

export type FaceImageQualityGroupsStrings = typeof FaceImageQualityGroupsStrings[keyof typeof FaceImageQualityGroupsStrings];



