/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FilterOp } from './filter-op';

/**
 * Allows you to filter search results by Person fields. Currently, filtering is supported only by the `name` field.
 */
export interface FilterSearchRequest {
    'op'?: FilterOp;
    /**
     * The Person field to which the filter is applied. Currently, only `name` is supported. If another field is specified, the filter is ignored.
     */
    'field'?: string;
    /**
     * The list of values against which the specified `field` is compared.
     */
    'value'?: Array<string>;
}



