/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FilterOp } from './filter-op';

/**
 * Allows to filter the search results based on the Person\'s `name`. If enabled, only the search results that meet the filter condition will be returned.
 */
export interface FilterSearchRequest {
    'op'?: FilterOp;
    /**
     * `name` of the Person.
     */
    'field'?: string;
    /**
     * The list of `name` values against which the `field` is compared.
     */
    'value'?: Array<string>;
}



