/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body of the group to create data, includes name and metadata.
 * @export
 * @interface GroupToCreate
 */
export interface GroupToCreate {
    /**
     * Group to create name.
     * @type {string}
     * @memberof GroupToCreate
     */
    'name'?: string;
    /**
     * A free-form object containing group\'s extended attributes.
     * @type {{ [key: string]: object; }}
     * @memberof GroupToCreate
     */
    'metadata'?: { [key: string]: object; };
}

