/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Response group create data, includes name and metadata.
 */
export interface GroupResponse {
    /**
     * Group to create name.
     */
    'name'?: string;
    /**
     * A free-form object containing group\'s extended attributes.
     */
    'metadata'?: { [key: string]: any; };
}

