/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Request body of the group to create data, includes name and metadata.
 */
export interface GroupToCreate {
    /**
     * Session identificator.
     */
    'tag'?: string;
    /**
     * Group to create name.
     */
    'name': string;
    /**
     * A free-form object containing group\'s extended attributes.
     */
    'metadata': { [key: string]: any; };
}

