/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Image } from './image';

/**
 * Image page.
 * @export
 * @interface ImagePageAllOf
 */
export interface ImagePageAllOf {
    /**
     * 
     * @type {Array<Image>}
     * @memberof ImagePageAllOf
     */
    'items'?: Array<Image>;
}

