/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face Recognition Web API
 * Regula Face Recognition Web API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageLivenessItem } from './image-liveness-item';

/**
 * 
 * @export
 * @interface ImageLiveness
 */
export interface ImageLiveness {
    /**
     * 
     * @type {Array<ImageLivenessItem>}
     * @memberof ImageLiveness
     */
    images?: Array<ImageLivenessItem>;
}


