/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageFieldsImage } from './image-fields-image';
// May contain unused imports in some cases
// @ts-ignore
import type { OutputImageParams } from './output-image-params';

/**
 * Image in the request data, includes image and contentType.
 */
export interface ImageFields {
    /**
     * Session identificator, should be unique for each session.
     */
    'tag'?: string;
    'image'?: ImageFieldsImage;
    'outputImageParams'?: OutputImageParams;
    /**
     * Whether to detect all faces in the image. If set to `false`, only the most central face is detected.
     */
    'detectAll'?: boolean;
    /**
     * The similarity threshold.
     */
    'threshold'?: number;
    /**
     * The maximum number of results to be returned. If not specified, the default value is 100.
     */
    'limit'?: number;
}

