/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Image in the response.
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * Response image ID.
     * @type {number}
     * @memberof Image
     */
    'id'?: number;
    /**
     * The original media type of the returned image.
     * @type {string}
     * @memberof Image
     */
    'content_type'?: string;
    /**
     * The returned image creation date.
     * @type {string}
     * @memberof Image
     */
    'created_at'?: string;
    /**
     * The returned image S3 path.
     * @type {string}
     * @memberof Image
     */
    'path'?: string;
    /**
     * The returned image URL.
     * @type {string}
     * @memberof Image
     */
    'url'?: string;
}

