/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ResizeOptions } from './resize-options';

/**
 * Uploaded image.
 */
export interface ImageFieldsImage {
    /**
     * Original media type of the uploaded image.
     */
    'contentType'?: string;
    /**
     * Base64-encoded image.
     */
    'content'?: string;
    /**
     * Image URL.
     */
    'imageUrl'?: string;
    'resizeOptions'?: ResizeOptions;
}

