/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageData } from './image-data';

/**
 * 
 * @export
 * @interface ImageFieldsImage
 */
export interface ImageFieldsImage {
    /**
     * 
     * @type {string}
     * @memberof ImageFieldsImage
     */
    'content_type'?: string;
    /**
     * 
     * @type {ImageData}
     * @memberof ImageFieldsImage
     */
    'content'?: ImageData;
}

