/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Face photo image source types: https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/image-source/
 */

export enum ImageSource {
    DOCUMENT_PRINTED = 1,
    DOCUMENT_RFID = 2,
    LIVE = 3,
    DOCUMENT_WITH_LIVE = 4,
    EXTERNAL = 5,
    GHOST = 6,
    BARCODE = 7
}



