/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageFieldsImage } from './image-fields-image';

/**
 * Image in the request data, includes image and content_type.
 * @export
 * @interface ImageFields
 */
export interface ImageFields {
    /**
     * 
     * @type {ImageFieldsImage}
     * @memberof ImageFields
     */
    'image'?: ImageFieldsImage;
}

