/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Image } from './image';
import { ImagePageAllOf } from './image-page-all-of';
import { Page } from './page';

/**
 * @type ImagePage
 * @export
 */
export type ImagePage = ImagePageAllOf & Page;



