/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Image in the response.
 */
export interface Image {
    /**
     * Response image ID. The list is sorted by decreasing ID value.
     */
    'id'?: string;
    /**
     * Base64-encoded image. Returned only if `withImages` is set to true in the request.
     */
    'content'?: string;
    /**
     * Original media type of the returned image.
     */
    'contentType'?: string;
    /**
     * Returned image creation date.
     */
    'createdAt'?: string;
    /**
     * Returned image update date.
     */
    'updatedAt'?: string;
    /**
     * Returned image path.
     */
    'path'?: string;
    /**
     * Returned image URL.
     */
    'url'?: string;
    /**
     * A free-form object containing person\'s extended attributes.
     */
    'metadata'?: { [key: string]: any; };
}

