/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {number}
     * @memberof Image
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    content_type?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    url?: string;
}


