/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Liveness detection can be performed in three modes: active `0`,  passive `1`, and passive with blink `2`. [Learn more](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/usage/liveness/#active-and-passive-modes)
 */

export enum LivenessType {
    ACTIVE = 0,
    PASSIVE = 1,
    PASSIVE_WITH_BLINK = 2
}



