/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MatchAndSearchRequestImagesItem } from './match-and-search-request-images-item';

export interface MatchAndSearchRequest {
    /**
     * Session identificator, should be unique for each session.
     */
    'tag'?: string;
    /**
     * An array of images to be processed. At least two images must be provided.
     */
    'images'?: Array<MatchAndSearchRequestImagesItem>;
    /**
     * IDs of the groups in which the search is performed.
     */
    'groupIds'?: Array<string>;
    /**
     * The similarity threshold.
     */
    'threshold'?: number;
    /**
     * The maximum number of results to be returned.
     */
    'limit'?: number;
    /**
     * A label used to group transactions by customers, applications, or other criteria.
     */
    'tenant'?: string;
    /**
     * A label used to differentiate transactions by development stages.
     */
    'env'?: string;
}

