/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageSource } from './image-source';
import { ImageData } from './image-data';

/**
 * 
 * @export
 * @interface MatchImage
 */
export interface MatchImage {
    /**
     * Image index used to identify input photos between themselves. If not specified, than input list index is used
     * @type {number}
     * @memberof MatchImage
     */
    index?: number;
    /**
     * 
     * @type {ImageSource}
     * @memberof MatchImage
     */
    type?: ImageSource;
    /**
     * 
     * @type {ImageData}
     * @memberof MatchImage
     */
    data: ImageData;
}


