/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MatchAndSearchResponseDataDetectionsItem } from './match-and-search-response-data-detections-item';
// May contain unused imports in some cases
// @ts-ignore
import type { MatchImageResult } from './match-image-result';

export interface MatchAndSearchResponseData {
    /**
     * The match and search results.
     */
    'results'?: Array<MatchImageResult>;
    /**
     * Server processing time, ms. Does not include the time taken to receive the request or deliver the response.
     */
    'elapsedTime'?: number;
    /**
     * A free-form object containing person\'s extended attributes.
     */
    'metadata'?: { [key: string]: any; };
    /**
     * The detection results.
     */
    'detections'?: Array<MatchAndSearchResponseDataDetectionsItem>;
}

