/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MatchImage } from './match-image';
// May contain unused imports in some cases
// @ts-ignore
import type { MatchRequestData } from './match-request-data';
// May contain unused imports in some cases
// @ts-ignore
import type { OutputImageParams } from './output-image-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionLabels } from './transaction-labels';

/**
 * @type MatchRequest
 */
export type MatchRequest = MatchRequestData & TransactionLabels;


