/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 4.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DetectionFace } from './detection-face';
import { FaceSDKResultCode } from './face-sdkresult-code';
import { PersonWithImages } from './person-with-images';

/**
 * 
 * @export
 * @interface MatchAndSearchResponseAllOfDetections
 */
export interface MatchAndSearchResponseAllOfDetections {
    /**
     * 
     * @type {Array<DetectionFace & object>}
     * @memberof MatchAndSearchResponseAllOfDetections
     */
    'faces'?: Array<DetectionFace & object>;
    /**
     * Image index used to identify input photos between themselves. If not specified, than input list index is used.
     * @type {number}
     * @memberof MatchAndSearchResponseAllOfDetections
     */
    'imageIndex'?: number;
    /**
     * 
     * @type {FaceSDKResultCode}
     * @memberof MatchAndSearchResponseAllOfDetections
     */
    'status'?: FaceSDKResultCode;
}

