/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DetectionFace } from './detection-face';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceSDKResultCode } from './face-sdkresult-code';

export interface MatchImageDetection {
    /**
     * Detected faces.
     */
    'faces'?: Array<DetectionFace>;
    /**
     * The image index number. Can be given; if not given, the index numbers are set automatically starting from `0`. All index numbers must be whole and unique—not repeated.
     */
    'imageIndex': number;
    'status': FaceSDKResultCode;
}



