/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageSource } from './image-source';

export interface MatchImage {
    /**
     * The image index number. Can be given; if not given, the index numbers are set automatically starting from `0`. All index numbers must be whole and unique—not repeated.
     */
    'index'?: number;
    'type'?: ImageSource;
    /**
     * Base64-encoded image.
     */
    'data': string;
    /**
     * Whether to detect all faces in the image. If set to `false`, only the most central face is detected.
     */
    'detectAll'?: boolean;
    /**
     * Identifier of the completed liveness transaction whose captured face is used as one of the comparison inputs. If this parameter is provided, it replaces one of the images in the matching request.
     */
    'livenessTransactionId'?: string;
}



