/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceSDKResult } from './face-sdkresult';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceSDKResultCode } from './face-sdkresult-code';
// May contain unused imports in some cases
// @ts-ignore
import type { MatchAndSearchResponseData } from './match-and-search-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { MatchAndSearchResponseDataDetectionsItem } from './match-and-search-response-data-detections-item';
// May contain unused imports in some cases
// @ts-ignore
import type { MatchImageResult } from './match-image-result';

/**
 * @type MatchAndSearchResponse
 */
export type MatchAndSearchResponse = FaceSDKResult & MatchAndSearchResponseData;


