/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageSource } from './image-source';

export interface MatchAndSearchRequestImagesItem {
    /**
     * Base64-encoded image.
     */
    'content'?: string;
    /**
     * Image URL.
     */
    'imageUrl'?: string;
    'type'?: ImageSource;
}



