/* tslint:disable */
/* eslint-disable */
/**
 * Regula Face SDK Web API
 * <a href=\"https://regulaforensics.com/products/face-recognition-sdk/  \" target=\"_blank\">Regula Face SDK</a> is a cross-platform biometric verification solution for a digital identity verification process and image quality assurance. The SDK enables convenient and reliable face capture on the client side (mobile, web, and desktop) and further processing on the client or server side.   The Face SDK includes the following features:  * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-detection\" target=\"_blank\">Face detection and image quality assessment</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-comparison-11\" target=\"_blank\">Face match (1:1)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-identification-1n\" target=\"_blank\">Face search (1:N)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#liveness-assessment\" target=\"_blank\">Liveness detection</a>  Here is the <a href=\"https://github.com/regulaforensics/FaceSDK-web-openapi  \" target=\"_blank\">OpenAPI specification on GitHub</a>.   ### Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MatchAndSearchRequestImagesInner } from './match-and-search-request-images-inner';

/**
 * 
 * @export
 * @interface MatchAndSearchRequest
 */
export interface MatchAndSearchRequest {
    /**
     * Session identificator, should be unique for each session.
     * @type {string}
     * @memberof MatchAndSearchRequest
     */
    'tag'?: string;
    /**
     * Person\'s images.
     * @type {Array<MatchAndSearchRequestImagesInner>}
     * @memberof MatchAndSearchRequest
     */
    'images'?: Array<MatchAndSearchRequestImagesInner>;
    /**
     * IDs of the groups in which the search is performed.
     * @type {Array<string>}
     * @memberof MatchAndSearchRequest
     */
    'groupIds'?: Array<string>;
    /**
     * The similarity threshold.
     * @type {number}
     * @memberof MatchAndSearchRequest
     */
    'threshold'?: number;
    /**
     * The maximum number of results to be returned.
     * @type {number}
     * @memberof MatchAndSearchRequest
     */
    'limit'?: number;
    /**
     * A label used to group transactions by customers, applications, or other criteria.
     * @type {string}
     * @memberof MatchAndSearchRequest
     */
    'tenant'?: string;
    /**
     * A label used to differentiate transactions by development stages.
     * @type {string}
     * @memberof MatchAndSearchRequest
     */
    'env'?: string;
}

