/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



export interface OperationLog {
    /**
     * Status code.
     */
    'statusCode'?: number;
    /**
     * Error type.
     */
    'type'?: string;
    /**
     * Error message.
     */
    'msg'?: string;
    /**
     * A free-form object containing group\'s extended attributes.
     */
    'metadata'?: { [key: string]: any; };
}

