/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OperationLog
 */
export interface OperationLog {
    /**
     * 
     * @type {number}
     * @memberof OperationLog
     */
    status_code?: number;
    /**
     * 
     * @type {string}
     * @memberof OperationLog
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationLog
     */
    msg?: string;
}


