/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Information about current page number and total pages count
 */
export interface Page {
    /**
     * Current page number.
     */
    'page'?: number;
    /**
     * Total number of pages.
     */
    'totalPages'?: number;
}

