/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Person } from './person';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonWithImagesData } from './person-with-images-data';
// May contain unused imports in some cases
// @ts-ignore
import type { RecognizeImage } from './recognize-image';

/**
 * @type PersonWithImages
 */
export type PersonWithImages = Person & PersonWithImagesData;


