/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecognizeImage } from './recognize-image';

export interface PersonWithImagesData {
    /**
     * Detected Persons.
     */
    'images'?: Array<RecognizeImage>;
}

