/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonData } from './person-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonFields } from './person-fields';

/**
 * @type Person
 * Person response body: person ID, creation date, update date if any.
 */
export type Person = PersonData & PersonFields;


