/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Page } from './page';
// May contain unused imports in some cases
// @ts-ignore
import type { Person } from './person';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonItems } from './person-items';

/**
 * @type PersonsPage
 */
export type PersonsPage = Page & PersonItems;


