/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Person Request body: name and metadata.
 */
export interface PersonFields {
    /**
     * Person\'s name.
     */
    'name': string;
    /**
     * Person\'s ID, used for linking search results to an ID in an external system. Can be set when creating a Person, stored in the database, and included in the search to return only Persons with the specified ID. Optional.
     */
    'externalId'?: string;
    /**
     * A free-form object containing person\'s extended attributes.
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Groups a person should be placed to. If no group is specified in request, a Default group is created and the person is placed to it.
     */
    'groups'?: Array<string>;
    /**
     * Person expiration date.
     */
    'expireAt'?: string;
}

