/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Person } from './person';

/**
 * 
 * @export
 * @interface PersonsPageAllOf
 */
export interface PersonsPageAllOf {
    /**
     * 
     * @type {Array<Person>}
     * @memberof PersonsPageAllOf
     */
    'items'?: Array<Person>;
}

