/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Person Request body: name and metadata.
 * @export
 * @interface PersonFields
 */
export interface PersonFields {
    /**
     * Person name.
     * @type {string}
     * @memberof PersonFields
     */
    'name'?: string;
    /**
     * A free-form object containing person\'s extended attributes.
     * @type {{ [key: string]: object; }}
     * @memberof PersonFields
     */
    'metadata'?: { [key: string]: object; };
}

