/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



export interface PersonData {
    /**
     * Person ID. The list of persons is sorted by decreasing ID value.
     */
    'id'?: string;
    /**
     * Person creation date.
     */
    'createdAt'?: string;
    /**
     * Person update date.
     */
    'updatedAt'?: string;
    /**
     * List of groups this person belongs to.
     */
    'groups'?: Array<string>;
}

