/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AttributeConfig } from './attribute-config';

/**
 * If set, the selected attributes, such as age or emotions, are evaluated. To check all the available attributes, you can set the `AttributesAll` scenario in `processParam.scenario`.
 */
export interface ProcessParamAttributes {
    /**
     * The list of attributes for evaluation.
     */
    'config'?: Array<AttributeConfig>;
}

