/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * [Download OpenAPI specification](https://github.com/regulaforensics/FaceSDK-web-openapi) ### Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FaceQualityScenarios } from './face-quality-scenarios';
// May contain unused imports in some cases
// @ts-ignore
import { OutputImageParams } from './output-image-params';
// May contain unused imports in some cases
// @ts-ignore
import { ProcessParamAttributes } from './process-param-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { QualityRequest } from './quality-request';

/**
 * The processing parameters.
 * @export
 * @interface ProcessParam
 */
export interface ProcessParam {
    /**
     * 
     * @type {FaceQualityScenarios}
     * @memberof ProcessParam
     */
    'scenario'?: FaceQualityScenarios;
    /**
     * Whether to process only the central face on the image (true) or all the faces (false).
     * @type {boolean}
     * @memberof ProcessParam
     */
    'onlyCentralFace'?: boolean;
    /**
     * 
     * @type {OutputImageParams}
     * @memberof ProcessParam
     */
    'outputImageParams'?: OutputImageParams;
    /**
     * 
     * @type {QualityRequest}
     * @memberof ProcessParam
     */
    'quality'?: QualityRequest;
    /**
     * 
     * @type {ProcessParamAttributes}
     * @memberof ProcessParam
     */
    'attributes'?: ProcessParamAttributes;
}



