/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceQualityScenarios } from './face-quality-scenarios';
import { OutputImageParams } from './output-image-params';
import { QualityRequest } from './quality-request';

/**
 * 
 * @export
 * @interface ProcessParam
 */
export interface ProcessParam {
    /**
     * 
     * @type {FaceQualityScenarios}
     * @memberof ProcessParam
     */
    scenario?: FaceQualityScenarios;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessParam
     */
    onlyCentralFace?: boolean;
    /**
     * 
     * @type {OutputImageParams}
     * @memberof ProcessParam
     */
    outputImageParams?: OutputImageParams;
    /**
     * 
     * @type {QualityRequest}
     * @memberof ProcessParam
     */
    quality?: QualityRequest;
}


