/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceQualityScenarios } from './face-quality-scenarios';
// May contain unused imports in some cases
// @ts-ignore
import type { OutputImageParams } from './output-image-params';
// May contain unused imports in some cases
// @ts-ignore
import type { ProcessParamAttributes } from './process-param-attributes';
// May contain unused imports in some cases
// @ts-ignore
import type { QualityRequest } from './quality-request';

/**
 * The processing parameters.
 */
export interface ProcessParam {
    'scenario'?: FaceQualityScenarios;
    /**
     * Whether to process only the central face in the image. If set to `false`, all the faces are processed.
     */
    'onlyCentralFace'?: boolean;
    'outputImageParams'?: OutputImageParams;
    'quality'?: QualityRequest;
    'attributes'?: ProcessParamAttributes;
}



