/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceQualityConfigName } from './face-quality-config-name';
import { FaceQualityUnit } from './face-quality-unit';

/**
 * 
 * @export
 * @interface QualityConfig
 */
export interface QualityConfig {
    /**
     * 
     * @type {FaceQualityConfigName}
     * @memberof QualityConfig
     */
    name?: FaceQualityConfigName;
    /**
     * 
     * @type {Array<number>}
     * @memberof QualityConfig
     */
    range?: Array<number>;
    /**
     * 
     * @type {FaceQualityUnit}
     * @memberof QualityConfig
     */
    unit?: FaceQualityUnit;
}


