/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceImageQualityGroups } from './face-image-quality-groups';

/**
 * 
 * @export
 * @interface QualityDetailsGroups
 */
export interface QualityDetailsGroups {
    /**
     * 
     * @type {FaceImageQualityGroups}
     * @memberof QualityDetailsGroups
     */
    groupId?: FaceImageQualityGroups;
    /**
     * The name of the characteristics group.
     * @type {string}
     * @memberof QualityDetailsGroups
     */
    name?: string;
    /**
     * The total number of characteristics in the group.
     * @type {number}
     * @memberof QualityDetailsGroups
     */
    totalCount?: number;
    /**
     * The number of compliant characteristics in the group.
     * @type {number}
     * @memberof QualityDetailsGroups
     */
    compliantCount?: number;
}


