/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceImageQualityGroups } from './face-image-quality-groups';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceImageQualityGroupsStrings } from './face-image-quality-groups-strings';

export interface QualityDetailsGroups {
    'groupId'?: FaceImageQualityGroups;
    'name'?: FaceImageQualityGroupsStrings;
    /**
     * The total number of characteristics in the group.
     */
    'totalCount'?: number;
    /**
     * The number of compliant characteristics in the group.
     */
    'compliantCount'?: number;
}



