/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceImageQualityGroups } from './face-image-quality-groups';
import { FaceQualityConfigName } from './face-quality-config-name';
import { FaceQualityStatus } from './face-quality-status';

/**
 * 
 * @export
 * @interface QualityDetail
 */
export interface QualityDetail {
    /**
     * 
     * @type {FaceImageQualityGroups}
     * @memberof QualityDetail
     */
    'groupId'?: FaceImageQualityGroups;
    /**
     * 
     * @type {FaceQualityConfigName}
     * @memberof QualityDetail
     */
    'name'?: FaceQualityConfigName;
    /**
     * The range of set values for this characteristic.
     * @type {Array<number>}
     * @memberof QualityDetail
     */
    'range'?: Array<number>;
    /**
     * 
     * @type {FaceQualityStatus}
     * @memberof QualityDetail
     */
    'status'?: FaceQualityStatus;
    /**
     * The assessed value for the characteristic, returned in the set units.
     * @type {number}
     * @memberof QualityDetail
     */
    'value'?: number;
}

