/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Align } from './align';
import { QualityConfig } from './quality-config';

/**
 * 
 * @export
 * @interface QualityRequest
 */
export interface QualityRequest {
    /**
     * 
     * @type {Align}
     * @memberof QualityRequest
     */
    align?: Align;
    /**
     * Array of RGB color
     * @type {Array<number>}
     * @memberof QualityRequest
     */
    background?: Array<number>;
    /**
     * 
     * @type {QualityConfig}
     * @memberof QualityRequest
     */
    config?: QualityConfig;
}


