/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QualityConfig } from './quality-config';

/**
 * If set, the face image quality check is performed according to the given list of [characteristics](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/usage/face-detection/face-image-quality-check/) in `quality.config`.
 */
export interface QualityRequest {
    /**
     * The RGB value of a color for filling background behind a person\'s silhouette and for aligning the image.
     */
    'backgroundMatchColor'?: Array<number>;
    /**
     * The list of quality check characteristics.
     */
    'config'?: Array<QualityConfig>;
}

