/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceImageQualityGroups } from './face-image-quality-groups';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceImageQualityStatus } from './face-image-quality-status';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceQualityConfigName } from './face-quality-config-name';

export interface QualityDetail {
    'groupId'?: FaceImageQualityGroups;
    'name'?: FaceQualityConfigName;
    /**
     * The range of set values for this characteristic, see the [Recommended range column](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/usage/face-detection/face-image-quality-check/).
     */
    'range'?: Array<number>;
    'status'?: FaceImageQualityStatus;
    /**
     * The result value for the characteristic, returned in set units.
     */
    'value'?: number;
}



