/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FaceQualityDetailsGroups } from './face-quality-details-groups';

/**
 * 
 * @export
 * @interface QualityDetailsGroups
 */
export interface QualityDetailsGroups {
    /**
     * 
     * @type {FaceQualityDetailsGroups}
     * @memberof QualityDetailsGroups
     */
    groupId?: FaceQualityDetailsGroups;
    /**
     * 
     * @type {string}
     * @memberof QualityDetailsGroups
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof QualityDetailsGroups
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof QualityDetailsGroups
     */
    compliant?: number;
}


