/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FilterSearchRequest } from './filter-search-request';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageFields } from './image-fields';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageFieldsImage } from './image-fields-image';
// May contain unused imports in some cases
// @ts-ignore
import type { OutputImageParams } from './output-image-params';
// May contain unused imports in some cases
// @ts-ignore
import type { SearchParameters } from './search-parameters';
// May contain unused imports in some cases
// @ts-ignore
import type { SearchParametersCreatePerson } from './search-parameters-create-person';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionLabels } from './transaction-labels';

/**
 * @type SearchRequest
 */
export type SearchRequest = ImageFields & SearchParameters & TransactionLabels;


