/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RecognizeImage } from './recognize-image';

/**
 * The array of Person images.
 * @export
 * @interface SearchPersonAllOf
 */
export interface SearchPersonAllOf {
    /**
     * 
     * @type {Array<RecognizeImage>}
     * @memberof SearchPersonAllOf
     */
    'images'?: Array<RecognizeImage>;
}

