/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



export interface SearchBadParams {
    'msg'?: string;
    'statusCode'?: number;
    'type'?: string;
}

