/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageFields } from './image-fields';
import { ImageFieldsImage } from './image-fields-image';
import { SearchRequestAllOf } from './search-request-all-of';

/**
 * @type SearchRequest
 * @export
 */
export type SearchRequest = ImageFields & SearchRequestAllOf;


