/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * The array of identified persons.
 */
export interface SearchDetection {
    /**
     * Internal.
     */
    'code'?: number;
    /**
     * Base64 of the aligned and cropped portrait.
     */
    'crop'?: string;
    /**
     * Internal.
     */
    'detectorType'?: number;
    /**
     * Internal.
     */
    'hash'?: string;
    /**
     * Internal.
     */
    'idx'?: number;
    /**
     * Internal.
     */
    'image'?: string;
    /**
     * Absolute coordinates (x,y) of five points of each detected face: left eye, right eye, nose, left point of lips, right point of lips.
     */
    'landmarks'?: Array<Array<number>>;
    /**
     * Internal.
     */
    'landmarksType'?: number;
    /**
     * Internal.
     */
    'msg'?: string;
    /**
     * The rectangular area of a detected face that is represented by a set of four elements: the X and Y coordinates of the top-left point, and the width and height dimensions of the rectangle.
     */
    'roi'?: Array<number>;
    'versionSDK'?: string;
}

