/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImageFields } from './image-fields';

/**
 * 
 * @export
 * @interface SearchRequest
 */
export interface SearchRequest {
    /**
     * 
     * @type {number}
     * @memberof SearchRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchRequest
     */
    threshold?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof SearchRequest
     */
    group_ids?: Array<number>;
    /**
     * 
     * @type {ImageFields}
     * @memberof SearchRequest
     */
    image?: ImageFields;
}


