/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionInfo
 */
export interface TransactionInfo {
    /**
     * Result code, one of the FaceSDKResultCode enum values. See the enum: https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/face-sdk-result-code/
     * @type {number}
     * @memberof TransactionInfo
     */
    'code'?: number;
    /**
     * Whether the liveness detection is confirmed (0) or not (1).
     * @type {number}
     * @memberof TransactionInfo
     */
    'status'?: number;
    /**
     * Session identificator.
     * @type {string}
     * @memberof TransactionInfo
     */
    'tag'?: string;
    /**
     * Transaction ID, there can be several transactions within one session.
     * @type {string}
     * @memberof TransactionInfo
     */
    'transactionId'?: string;
    /**
     * Link to the session video.
     * @type {string}
     * @memberof TransactionInfo
     */
    'video'?: string;
    /**
     * Approximate age with an accuracy of +/-3 years.
     * @type {number}
     * @memberof TransactionInfo
     */
    'age'?: number;
    /**
     * Link to the portrait.
     * @type {string}
     * @memberof TransactionInfo
     */
    'portrait'?: string;
    /**
     * A free-form object containing person\'s extended attributes.
     * @type {{ [key: string]: object; }}
     * @memberof TransactionInfo
     */
    'metadata'?: { [key: string]: object; };
}

