/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnrollResult } from './enroll-result';
// May contain unused imports in some cases
// @ts-ignore
import type { LivenessType } from './liveness-type';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyResult } from './verify-result';

export interface TransactionInfo {
    /**
     * Result code, see the [FaceSDKResultCode enum](https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/face-sdk-result-code/).
     */
    'code'?: number;
    /**
     * Whether the liveness detection is confirmed `0` or not `1`.
     */
    'status'?: number;
    /**
     * Session identificator, should be unique for each session.
     */
    'tag'?: string;
    /**
     * Transaction ID, there can be several transactions within one session.
     */
    'transactionId'?: string;
    /**
     * Link to the session video, depends on the selected storage type. [Learn more](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/storage/)
     */
    'video'?: string;
    /**
     * Approximate age with an accuracy of +/-3 years.
     */
    'age'?: Array<{ [key: string]: any; }>;
    /**
     * Link to the portrait, depends on the selected storage type. [Learn more](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/storage/)
     */
    'portrait'?: string;
    /**
     * A free-form object containing the Person\'s extended attributes.
     */
    'metadata'?: { [key: string]: any; };
    'type'?: LivenessType;
    'enrollResult'?: EnrollResult;
    'verifyResult'?: VerifyResult;
}



