/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



export interface TransactionLabels {
    /**
     * A label used to group transactions by customers, applications, or other criteria.
     */
    'tenant'?: string;
    /**
     * A label used to differentiate transactions by development stages.
     */
    'env'?: string;
}

