/* tslint:disable */
/* eslint-disable */
/**
 * Regula FaceSDK Web API
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Update group.
 * @export
 * @interface UpdateGroup
 */
export interface UpdateGroup {
    /**
     * Add items.
     * @type {Array<number>}
     * @memberof UpdateGroup
     */
    'addItems'?: Array<number>;
    /**
     * Remove items.
     * @type {Array<number>}
     * @memberof UpdateGroup
     */
    'removeItems'?: Array<number>;
}

