/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Update group.
 */
export interface UpdateGroup {
    /**
     * Add items.
     */
    'addItems'?: Array<string>;
    /**
     * Remove items.
     */
    'removeItems'?: Array<string>;
}

